[package]
name = "recap"
version = "0.1.0"
edition = "2024"

[dependencies]
error = "0.1.9"
serde = { version = "1.0.228", features = ["serde_derive", "std"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
uuid = { version = "1.18.1", features = ["serde", "v4"] }
