[package]
name = "Phase2"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
error = "0.1.9"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
